### ISSUE TITLE
Building Lumina from source on Debian fails et al

### ISSUE THREAD

**Issue by pommetjehorlepiep** [trueos/lumina#258]
OS: Debian 8 Jessie
Branch: qt5/1.0.0

Following the instructions on https://lumina-desktop.org/get-lumina/, section '**Building Lumina from source on Debian/Ubuntu/Linux Mint**', I ran into the following 2 issues:

1. **qmake** doesn't return a message although apparently expected. Build seems to work ok though...
2. The **make** step fails with following error:

In file included from ScreenSettings.cpp:7:0:
ScreenSettings.h:22:14: error: field ‘resList’ has incomplete type ‘QStringList’
  QStringList resList;
                ^
		Makefile:362: recipe for target 'ScreenSettings.o' failed
		make[3]: *** [ScreenSettings.o] Error 1
		make[3]: Leaving directory '/root/lumina/src-qt5/core-utils/lumina-xconfig'
		Makefile:90: recipe for target 'sub-lumina-xconfig-make_first' failed
		make[2]: *** [sub-lumina-xconfig-make_first] Error 2
		make[2]: Leaving directory '/root/lumina/src-qt5/core-utils'
		Makefile:65: recipe for target 'sub-core-utils-make_first' failed
		make[1]: *** [sub-core-utils-make_first] Error 2
		make[1]: Leaving directory '/root/lumina/src-qt5'
		Makefile:38: recipe for target 'sub-src-qt5-make_first' failed
		make: *** [sub-src-qt5-make_first] Error 2

**Comment by beanpole135** [comment]
Fixed!
This fix was also backported to the qt5/1.0.0 branch.

https://github.com/trueos/lumina/commit/68e81cdf38713077a04d784a986655ebd4da662f

**Comment by pommetjehorlepiep** [comment]
Confirmed as fixed.....but build is still failing...  :(
Raised new issue: #260

**Comment by pommetjehorlepiep** [comment]
With the fix for #260 you will be able to successfully build Lumina on Debian 8 Jessie from source (master).
