### ISSUE TITLE
Lumina start menu icon at top left, menu items in the right-hand half of the screen with an expanse of grey to their left

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#300]
Bugging an admin account that I rarely use, this shot was taken on 2016-11-06:

![2016-11-06-21-58-07](https://cloud.githubusercontent.com/assets/192271/20242692/f50725cc-a92f-11e6-99b0-76715a16675e.png)

I can't tell when the bug began, nor can I imagine how it might be made reproducible … sorry. 

----

Afterthought, maybe worth mentioning: this is on an HP EliteBook 850G2 notebook where TrueOS Desktop never drives the display that's integral to the notebook. It drives: 

- at home, a VGA display at DP-2 with a resolution of 1,366x768 pixels
- at work, when docked, two displays on DisplayPort and one of the two is much larger (maybe 1,900x1,200).

**Comment by q5sys** [comment]
I thought the menu size thing should be fixed now.  Do you know what version of Lumina you are running on that machine?

**Comment by q5sys** [comment]
Since you've updated Lumina, are you still having this problem?

**Comment by grahamperrin** [comment]
Yes, with 1.1.2 (Git Revision: d5a55a0).

With the customised panel at the top, the problem persisted, so I added a panel at the bottom. 

The panel at the top unexpectedly disappeared, that's probably another symptom of #304.

A shot of start menu in the new, default panel 1 at the bottom: 

![bottom](https://cloud.githubusercontent.com/assets/192271/20461814/87bdc2be-af01-11e6-8a79-78b2a19ec256.png)

**Comment by grahamperrin** [comment]
With a different user 'test', on the same computer, the symptom is not evident: 

![test](https://cloud.githubusercontent.com/assets/192271/20461875/eb58dbea-af03-11e6-966f-c6aaaf74d039.png)

I'll review the display preferences for the original user …

**Comment by beanpole135** [comment]
The start menu keeps/re-uses it's last size information the next time it is started up (~/.config/lumina-desktop/pluginsettings/desktopsettings.conf` - look for the `[panelPlugs]` section).
You probably just expanded the menu as large as possible when testing something out. You should be able to grab one of the menu edges and resize it smaller again as well.

**Comment by grahamperrin** [comment]
No recollection of ever expanding the menu, I had no idea it was possible. 

> … You should be able to grab one of the menu edges and resize it smaller again as well.

Yep, I found the top left corner easiest to grab, pull down and to the right until the menu was entirely disconnected from its icon. Disconcerting, but it had the required effect after I allowed the menu disappear. 

Thanks

**Comment by BenjaminHCCarr** [comment]
My `admin`/`wheel` account (first created) still has this bug. 

At 640x480 and 800x600 the app launcher is "double wide". At 1024x768 it works fine. This is run in 
VirtualBox `Version 5.1.12 r112440` with `extensions` on an OS X 10.11.6 host.

VBox Screenshot:
![screen shot 2017-01-12 at 3 32 19 pm](https://cloud.githubusercontent.com/assets/8225968/21907482/c16140b2-d8dd-11e6-9169-e4753add6a96.png)
